import 'dart:convert';

class AnalisisIA {
  final bool esValido;
    final String prioridad;
      final String categoriaSugerida;
        final String justificacion;
          final DateTime fechaAnalisis;

            AnalisisIA({
                required this.esValido,
                    required this.prioridad,
                        required this.categoriaSugerida,
                            required this.justificacion,
                                required this.fechaAnalisis,
                                  });

                                  factory AnalisisIA.fromJson(dynamic raw) {
                                      if (raw == null) {
                                            return AnalisisIA(
                                                    esValido: false,
                                                            prioridad: 'baja',
                                                                    categoriaSugerida: 'Desconocida',
                                                                            justificacion: 'No se proporcionó justificación.',
                                                                                    fechaAnalisis: DateTime.now(),
                                                                                          );
                                                                                              }

                                                                                                  Map<String, dynamic> json;
                                                                                                      if (raw is String) {
                                                                                                            try {
                                                                                                                    final parsed = jsonDecode(raw);
                                                                                                                            json = parsed is Map<String, dynamic> ? parsed : {'raw': raw};
                                                                                                                                  } catch (_) {
                                                                                                                                          json = {'raw': raw};
                                                                                                                                                }
                                                                                                                                                    } else if (raw is Map) {
                                                                                                                                                          json = Map<String, dynamic>.from(raw);
                                                                                                                                                              } else if (raw is List) {
                                                                                                                                                                    // Supabase puede pasar una lista aquí si el fromJson se llama directamente
                                                                                                                                                                          if (raw.isEmpty) {
                                                                                                                                                                                  return AnalisisIA(
                                                                                                                                                                                            esValido: false,
                                                                                                                                                                                                      prioridad: 'baja',
                                                                                                                                                                                                                categoriaSugerida: 'Desconocida',
                                                                                                                                                                                                                          justificacion: 'No se proporcionó justificación.',
                                                                                                                                                                                                                                    fechaAnalisis: DateTime.now(),
                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                        final first = raw.first;
                                                                                                                                                                                                                                                              json = first is Map<String, dynamic>
                                                                                                                                                                                                                                                                        ? first
                                                                                                                                                                                                                                                                                  : {'raw': first.toString()};
                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                    json = Map<String, dynamic>.from(raw as dynamic);
                                                                                                                                                                                                                                                                                                          } catch (_) {
                                                                                                                                                                                                                                                                                                                  json = {'raw': raw.toString()};
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                return AnalisisIA(
                                                                                                                                                                                                                                                                                                                                      esValido: json['es_valido'] == true,
                                                                                                                                                                                                                                                                                                                                            prioridad: json['prioridad']?.toString() ?? 'baja',
                                                                                                                                                                                                                                                                                                                                                  categoriaSugerida: json['categoria_sugerida']?.toString() ?? 'Desconocida',
                                                                                                                                                                                                                                                                                                                                                        justificacion: json['justificacion']?.toString() ??
                                                                                                                                                                                                                                                                                                                                                                  'No se proporcionó justificación.',
                                                                                                                                                                                                                                                                                                                                                                        fechaAnalisis: json['fecha_analisis'] != null
                                                                                                                                                                                                                                                                                                                                                                                  ? DateTime.tryParse(json['fecha_analisis'].toString()) ?? DateTime.now()
                                                                                                                                                                                                                                                                                                                                                                                            : DateTime.now(),
                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                  Map<String, dynamic> toJson() {
                                                                                                                                                                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                                                                                                                                                                            'es_valido': esValido,
                                                                                                                                                                                                                                                                                                                                                                                                                  'prioridad': prioridad,
                                                                                                                                                                                                                                                                                                                                                                                                                        'categoria_sugerida': categoriaSugerida,
                                                                                                                                                                                                                                                                                                                                                                                                                              'justificacion': justificacion,
                                                                                                                                                                                                                                                                                                                                                                                                                                    'fecha_analisis': fechaAnalisis.toIso8601String(),
                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                            String toJsonString() => jsonEncode(toJson());
                                                                                                                                                                                                                                                                                                                                                                                                                                              @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                String toString() => toJsonString();
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                