
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../models/usuario_simple.dart';
import '../../providers/reportes_provider.dart';
import '../../core/constants/app_colors.dart';
import '../../shared/widgets/loading_widget.dart';

/// Diálogo para seleccionar un funcionario y asignarle un reporte.
class AsignacionDialog extends StatefulWidget {
  final String reporteId;
    const AsignacionDialog({super.key, required this.reporteId});

      @override
        State<AsignacionDialog> createState() => _AsignacionDialogState();
        }

        class _AsignacionDialogState extends State<AsignacionDialog> {
          UsuarioSimple? _funcionarioSeleccionado;

            @override
              void initState() {
                  super.initState();
                      // Carga la lista de funcionarios al abrir el diálogo.
                          WidgetsBinding.instance.addPostFrameCallback((_) {
                                context.read<ReportesProvider>().fetchFuncionarios();
                                    });
                                      }

                                        Future<void> _asignar() async {
                                            if (_funcionarioSeleccionado == null) {
                                                  ScaffoldMessenger.of(context).showSnackBar(
                                                          const SnackBar(content: Text('Por favor, seleccione un funcionario.')),
                                                                );
                                                                      return;
                                                                          }

                                                                              final provider = context.read<ReportesProvider>();
                                                                                  final success = await provider.crearAsignacion(
                                                                                        reporteId: widget.reporteId,
                                                                                              funcionarioId: _funcionarioSeleccionado!.id,
                                                                                                  );

                                                                                                      if (mounted) {
                                                                                                            if (success) {
                                                                                                                    ScaffoldMessenger.of(context).showSnackBar(
                                                                                                                              const SnackBar(content: Text('Reporte asignado con éxito.')),
                                                                                                                                      );
                                                                                                                                              Navigator.of(context).pop(true); // Cierra el diálogo y retorna éxito
                                                                                                                                                    } else {
                                                                                                                                                            ScaffoldMessenger.of(context).showSnackBar(
                                                                                                                                                                      SnackBar(content: Text('Error al asignar: ${provider.error}')),
                                                                                                                                                                              );
                                                                                                                                                                                    }
                                                                                                                                                                                        }
                                                                                                                                                                                          }

                                                                                                                                                                                            @override
                                                                                                                                                                                              Widget build(BuildContext context) {
                                                                                                                                                                                                  final provider = context.watch<ReportesProvider>();

                                                                                                                                                                                                      return AlertDialog(
                                                                                                                                                                                                            backgroundColor: AppColors.background,
                                                                                                                                                                                                                  title: const Text('Asignar Reporte', style: TextStyle(color: AppColors.textPrimary)),
                                                                                                                                                                                                                        content: provider.isLoading && provider.funcionarios.isEmpty
                                                                                                                                                                                                                                  ? const LoadingWidget(message: 'Cargando funcionarios...')
                                                                                                                                                                                                                                            : _buildDropdown(provider.funcionarios),
                                                                                                                                                                                                                                                  actions: <Widget>[
                                                                                                                                                                                                                                                          TextButton(
                                                                                                                                                                                                                                                                    child: const Text('Cancelar'),
                                                                                                                                                                                                                                                                              onPressed: () => Navigator.of(context).pop(),
                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                              ElevatedButton(
                                                                                                                                                                                                                                                                                                        style: ElevatedButton.styleFrom(backgroundColor: AppColors.primary),
                                                                                                                                                                                                                                                                                                                  onPressed: provider.isLoading ? null : _asignar,
                                                                                                                                                                                                                                                                                                                            child: provider.isLoading 
                                                                                                                                                                                                                                                                                                                                            ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2)) 
                                                                                                                                                                                                                                                                                                                                                            : const Text('Asignar'),
                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                  Widget _buildDropdown(List<UsuarioSimple> funcionarios) {
                                                                                                                                                                                                                                                                                                                                                                                      if (funcionarios.isEmpty) {
                                                                                                                                                                                                                                                                                                                                                                                              return const Text('No se encontraron funcionarios disponibles.');
                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                      return DropdownButtonFormField<UsuarioSimple>(
                                                                                                                                                                                                                                                                                                                                                                                                            value: _funcionarioSeleccionado,
                                                                                                                                                                                                                                                                                                                                                                                                                  hint: const Text('Seleccione un funcionario'),
                                                                                                                                                                                                                                                                                                                                                                                                                        onChanged: (UsuarioSimple? newValue) {
                                                                                                                                                                                                                                                                                                                                                                                                                                setState(() {
                                                                                                                                                                                                                                                                                                                                                                                                                                          _funcionarioSeleccionado = newValue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                              items: funcionarios.map<DropdownMenuItem<UsuarioSimple>>((UsuarioSimple funcionario) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return DropdownMenuItem<UsuarioSimple>(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value: funcionario,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: Text(funcionario.nombre),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }).toList(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  contentPadding: EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              